# Exported from Render on 2024-09-17T12:05:41Z
services:
  - type: web
    name: homemanage
    runtime: node
    repo: https://github.com/avipatel001/homemanage-backend
    plan: free
    envVars:
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        sync: false
    region: oregon
    buildCommand: npm install
    startCommand: node index.js
    rootDir: ./src
version: "1"
